import {CTGHistory, CTGHistoryDTO, HistoryStatus} from "@entities/ctg-history/model/types";

export const mockHistory: CTGHistoryDTO[] = [{
  id: 1,
  date: "2025-08-19",
  gestation: "40+0 нед",
  hr: 142,
  uc: 10,
  stv: 3.3,
  acceleration: 3,
  figo: HistoryStatus.Pathological,
  forecast: HistoryStatus.Normal,
},
  {
    id: 2,
    date: "2025-08-12",
    gestation: "39+1 нед",
    hr: 157,
    uc: 21,
    stv: 5.3,
    acceleration: 4,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 3,
    date: "2025-08-12",
    gestation: "40+2 нед",
    hr: 127,
    uc: 14,
    stv: 4.3,
    acceleration: 1,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 4,
    date: "2025-08-03",
    gestation: "37+5 нед",
    hr: 122,
    uc: 6,
    stv: 3.5,
    acceleration: 4,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 5,
    date: "2025-08-09",
    gestation: "38+6 нед",
    hr: 157,
    uc: 46,
    stv: 4.4,
    acceleration: 5,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Preterminal,
  },
  {
    id: 6,
    date: "2025-08-09",
    gestation: "39+2 нед",
    hr: 135,
    uc: 25,
    stv: 4.6,
    acceleration: 2,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 7,
    date: "2025-08-01",
    gestation: "40+4 нед",
    hr: 124,
    uc: 21,
    stv: 4.7,
    acceleration: 4,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 8,
    date: "2025-08-11",
    gestation: "38+0 нед",
    hr: 129,
    uc: 27,
    stv: 4.0,
    acceleration: 2,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 9,
    date: "2025-08-16",
    gestation: "37+0 нед",
    hr: 133,
    uc: 38,
    stv: 2.1,
    acceleration: 2,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 10,
    date: "2025-08-16",
    gestation: "40+1 нед",
    hr: 138,
    uc: 46,
    stv: 5.7,
    acceleration: 5,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 11,
    date: "2025-08-07",
    gestation: "38+6 нед",
    hr: 154,
    uc: 33,
    stv: 3.0,
    acceleration: 1,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 12,
    date: "2025-08-01",
    gestation: "38+6 нед",
    hr: 128,
    uc: 37,
    stv: 5.1,
    acceleration: 1,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 13,
    date: "2025-08-07",
    gestation: "39+6 нед",
    hr: 123,
    uc: 40,
    stv: 5.5,
    acceleration: 5,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 14,
    date: "2025-08-10",
    gestation: "40+4 нед",
    hr: 117,
    uc: 24,
    stv: 2.2,
    acceleration: 1,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 15,
    date: "2025-08-08",
    gestation: "38+3 нед",
    hr: 157,
    uc: 27,
    stv: 2.1,
    acceleration: 2,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Doubtful,
  }];
