import {CTGHistory, HistoryStatus} from "@entities/ctg-history/model/types";

export const mockHistory: CTGHistory[] = [
  {
    id: 1,
    date: new Date("2025-08-04"),
    gestation: "40+1 нед",
    hr: 114,
    uc: 18,
    stv: 3.5,
    acceleration: 1,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 2,
    date: new Date("2025-08-09"),
    gestation: "40+4 нед",
    hr: 148,
    uc: 22,
    stv: 7.3,
    acceleration: 1,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 3,
    date: new Date("2025-08-08"),
    gestation: "38+6 нед",
    hr: 123,
    uc: 48,
    stv: 5.4,
    acceleration: 1,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 4,
    date: new Date("2025-08-04"),
    gestation: "37+6 нед",
    hr: 148,
    uc: 20,
    stv: 6.2,
    acceleration: 1,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 5,
    date: new Date("2025-08-13"),
    gestation: "40+6 нед",
    hr: 143,
    uc: 32,
    stv: 3.7,
    acceleration: 4,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Preterminal,
  },
  {
    id: 6,
    date: new Date("2025-08-18"),
    gestation: "40+6 нед",
    hr: 133,
    uc: 31,
    stv: 5.3,
    acceleration: 5,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 7,
    date: new Date("2025-08-03"),
    gestation: "37+0 нед",
    hr: 140,
    uc: 47,
    stv: 9.7,
    acceleration: 0,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 8,
    date: new Date("2025-08-01"),
    gestation: "38+3 нед",
    hr: 125,
    uc: 35,
    stv: 2.3,
    acceleration: 3,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 9,
    date: new Date("2025-08-09"),
    gestation: "40+2 нед",
    hr: 119,
    uc: 24,
    stv: 6.5,
    acceleration: 3,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 10,
    date: new Date("2025-08-11"),
    gestation: "37+4 нед",
    hr: 126,
    uc: 46,
    stv: 7.7,
    acceleration: 0,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Preterminal,
  },
  {
    id: 11,
    date: new Date("2025-08-05"),
    gestation: "40+1 нед",
    hr: 110,
    uc: 44,
    stv: 2.1,
    acceleration: 2,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 12,
    date: new Date("2025-08-10"),
    gestation: "39+2 нед",
    hr: 143,
    uc: 33,
    stv: 7.4,
    acceleration: 0,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Preterminal,
  },
  {
    id: 13,
    date: new Date("2025-08-01"),
    gestation: "38+0 нед",
    hr: 140,
    uc: 23,
    stv: 5.0,
    acceleration: 4,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 14,
    date: new Date("2025-08-11"),
    gestation: "38+0 нед",
    hr: 126,
    uc: 46,
    stv: 3.3,
    acceleration: 0,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 15,
    date: new Date("2025-08-14"),
    gestation: "39+0 нед",
    hr: 152,
    uc: 30,
    stv: 2.2,
    acceleration: 3,
    figo: HistoryStatus.Preterminal,
    forecast: HistoryStatus.Preterminal,
  },
  {
    id: 16,
    date: new Date("2025-08-14"),
    gestation: "39+0 нед",
    hr: 152,
    uc: 30,
    stv: 2.2,
    acceleration: 3,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Preterminal,
  }
];
