import {CTGHistory, HistoryStatus} from "@entities/ctg-history/model/types";

export const mockHistory: CTGHistory[] = [
  {
    id: 1,
    date: new Date("2025-08-07"),
    gestation: "38+2 нед",
    hr: 130,
    uc: 12,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Doubtful,
  },
  {
    id: 2,
    date: new Date("2025-08-07"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 3,
    date: new Date("2025-08-08"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Doubtful,
    forecast: HistoryStatus.Pathological,
  },
  {
    id: 4,
    date: new Date("2025-08-08"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 5,
    date: new Date("2025-08-09"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 6,
    date: new Date("2025-08-10"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 7,
    date: new Date("2025-08-11"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 8,
    date: new Date("2025-08-12"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 9,
    date: new Date("2025-08-13"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 10,
    date: new Date("2025-08-14"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 11,
    date: new Date("2025-08-15"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 12,
    date: new Date("2025-08-15"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 13,
    date: new Date("2025-08-16"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Pathological,
    forecast: HistoryStatus.Normal,
  },
  {
    id: 14,
    date: new Date("2025-08-17"),
    gestation: "38+1 нед",
    hr: 140,
    uc: 15,
    figo: HistoryStatus.Normal,
    forecast: HistoryStatus.Normal,
  },
];
